### ISSUE TITLE
Available free space size 240MB or 82MB?

### ISSUE THREAD

**Issue by meast** [dangowrt/linksys-e8450-openwrt-installer#13]
after execute `sysupgrade -F openwrt-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery-installer.itb`, there is about 240MB free space. and about 82MB after upload `openwrt-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb`.
there is no `kmod-mt7915e` included in `openwrt-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery-installer.itb`.

**Comment by dangowrt** [comment]
> after execute `sysupgrade -F openwrt-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery-installer.itb`, there is about 240MB free space.

The device only got a total of 128 MiB NAND flash. What you are seeing after running the installer is the recovery system which is running fully in RAM, hence the free space you see there is space in RAM (ie. volatile) rather than in flash.

> and about 82MB after upload `openwrt-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb`.

That's the expected free **flash** space after installation completed.

> there is no `kmod-mt7915e` included in `openwrt-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery-installer.itb`.

There is no need for the recovery image to come with a wifi driver.
It's meant only for installing and recovery, will never store any settings (such as actually enabling wifi) and generally you should use it over a wire.

**Comment by meast** [comment]
thank you.
